### ISSUE TITLE
stuck at Loading CMake Tools from source/path/.vscode/.cmaketools.json

### ISSUE THREAD

**Issue by ArtBlnd** [vector-of-bool/vscode-cmake-tools#181]
after uninstalling Visual Studio and reinstalling.
it doesn't work. just stuck at "Loading CMake Tools from source/path/.vscode/.cmaketools.json"
also not generating ".cmaketools.json" file

```
Invalid backend promise: Error: Invalid backend promise
    at new CMakeToolsWrapper (C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\wrapper.js:46:40)
    at C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:17:23
    at Generator.next (<anonymous>)
    at C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:7:65
    at __awaiter (C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:3:12)
    at activate (C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:15:12)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:418399)
    at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:418184)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:417959
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:39252)
```

```
Error in script usage. The correct usage is:: AssertionError: Error in script usage. The correct usage is:
    at Console.assert (console.js:95:23)
    at output.split.map.filter.reduce (C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\environment.js:74:21)
    at Array.reduce (native)
    at C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\environment.js:72:14
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ArtBlnd\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\environment.js:4:58)
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
```

Error on debugging mode

**Comment by ytimenkov** [comment]
@ArtBlnd What visual studio version do you have? Is it possible to run Developer Command prompt and providing output of `set` command (dumps your environment variables)?

**Comment by ytimenkov** [comment]
@ArtBlnd Are you running 32-bit system? Is it possible to run
`"c:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\vcvarsall.bat" amd64_arm` (or analog for your version)?

**Comment by ytimenkov** [comment]
In any case I'm fairly certain that second commit to #182 should fix this problem.

**Comment by ArtBlnd** [comment]
Im running on AMD64 Windows 10.0.15063

**Comment by ArtBlnd** [comment]
```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\ArtBlnd\AppData\Roaming
asl.log=Destination=file
CommandPromptType=Native
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=ARTBLND
ComSpec=C:\WINDOWS\system32\cmd.exe
DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\
ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
Framework40Version=v4.0
FrameworkDir=C:\WINDOWS\Microsoft.NET\Framework\
FrameworkDIR32=C:\WINDOWS\Microsoft.NET\Framework\
FrameworkVersion=v4.0.30319
FrameworkVersion32=v4.0.30319
HOMEDRIVE=C:
HOMEPATH=\Users\ArtBlnd
IFCPATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ifc\x86
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt;
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_111\
LIB=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\lib\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x86;
LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\lib\x86;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\;C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;
LOCALAPPDATA=C:\Users\ArtBlnd\AppData\Local
LOGONSERVER=\\ARTBLND
NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\ArtBlnd\OneDrive
OS=Windows_NT
Path=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\ArtBlnd\AppData\Local\Programs\Python\Python35-32;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\Program Files (x86)\LLVM\bin;C:\Program Files\TortoiseSVN\bin;C:\gnuwin32\bin;C:\Program Files\CMake\bin;C:\gnuwin32\lib;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Users\ArtBlnd\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ArtBlnd\AppData\Local\Microsoft\WindowsApps
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4e03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\ArtBlnd\AppData\Local\Temp
TMP=C:\Users\ArtBlnd\AppData\Local\Temp
TrinityPath=C:\Users\ArtBlnd\AppData\Local\Microsoft\VisualStudio\15.0_24692f7a\Extensions\5oipkixm.tic\Binaries
UCRTVersion=10.0.15063.0
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
USERDOMAIN=ARTBLND
USERDOMAIN_ROAMINGPROFILE=ARTBLND
USERNAME=ArtBlnd
USERPROFILE=C:\Users\ArtBlnd
VCIDEInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\
VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\
VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.10.25017\
VisualStudioVersion=15.0
VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\Common7\Tools\
VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_HOST_ARCH=x86
VSCMD_ARG_TGT_ARCH=x86
VSCMD_VER=15.0.26430.13
VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\
windir=C:\WINDOWS
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\;C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSDKLibVersion=10.0.15063.0\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\
WindowsSDKVersion=10.0.15063.0\
WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\
WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\
__DOTNET_ADD_32BIT=1
__DOTNET_PREFERRED_BITNESS=32
__VSCMD_PREINIT_PATH=C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\ArtBlnd\AppData\Local\Programs\Python\Python35-32;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\Program Files (x86)\LLVM\bin;C:\Program Files\TortoiseSVN\bin;C:\gnuwin32\bin;C:\Program Files\CMake\bin;C:\gnuwin32\lib;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Users\ArtBlnd\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ArtBlnd\AppData\Local\Microsoft\WindowsApps
```

My Visual Studio Environment

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
