### ISSUE TITLE
CMakeTools extension was unable to be initialized: AssertionError: Error in script usage.

### ISSUE THREAD

**Issue by marco9999** [vector-of-bool/vscode-cmake-tools#185]
I'm not sure what brought this on, but CMakeTools is now giving me errors when trying to do anything. It was working fine before, and on my other computer it also works fine... Although I'm not sure if it has a different version installed.

This error occurs on start-up:
```
shell.ts:445 Invalid backend promise: Error: Invalid backend promise
    at new CMakeToolsWrapper (C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\wrapper.js:46:40)
    at C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:17:23
    at Generator.next (<anonymous>)
    at C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:7:65
    at __awaiter (C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:3:12)
    at activate (C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\extension.js:15:12)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:418399)
    at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:418184)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:417959
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:39252)
```

This error occurs on trying to configure:
```
shell.ts:445 Error in script usage. The correct usage is:: AssertionError: Error in script usage. The correct usage is:
    at Console.assert (console.js:95:23)
    at output.split.map.filter.reduce (C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\environment.js:74:21)
    at Array.reduce (native)
    at C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\environment.js:72:14
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Marco\.vscode\extensions\vector-of-bool.cmake-tools-0.10.0\out\src\environment.js:4:58)
```
Possibly related to issues #170, #183 and #184 .

**Comment by ytimenkov** [comment]
It is likely duplicate of #181.
I suspect that there is some parts of VS 2015 are installed (Windows 8.1 development or similar) which cause vcvarsall fail with unexpected message.
Unfortunately CMake Tools treat this as a fatal error.
If you have VS 2017, you could try removing `VS140COMNTOOLS` environment variable before running VS Code to work around this problem.

**Comment by marco9999** [comment]
Yep, that works. Do you know if removing that env var permanently will screw up anything else? I dont have VS 2015/14.0 installed (or the build tools), so not sure why its set anyway.

**Comment by ytimenkov** [comment]
> Do you know if removing that env var permanently will screw up anything else

Only if you have something which depends on it. E.g. some project which has scripts as build system.
AFAIK msbuild doesn't use it.
Besides, *Developer command prompt* initializes them again in the session.

**Comment by marco9999** [comment]
Nope, don't have anything I know of that needs it. Thanks for your help!
