### ISSUE TITLE
Invalid backend promise

### ISSUE THREAD

**Issue by jas99** [vector-of-bool/vscode-cmake-tools#237]
Firstly I was trying extension with visual c++ 2015 buildtools and it was working great. Then I tried to run build to x64 but under vscode ran from 32bit visual c++ cmd. Now I am getting the following error. I have even uninstalled visual c++ 2015 buildtools and installed visual c++ 2017 community edition. Nothing seems to work.

```
extensionHost.ts:384 [Extension Host] Detecting environment: Visual Studio Community 2017 - x86
extensionHost.ts:384 [Extension Host] Detecting environment: Visual Studio Community 2017 - amd64
shell.ts:419 [vector-of-bool.cmake-tools] Invalid backend promise: Error: Invalid backend promise
	at new CMakeToolsWrapper (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\wrapper.js:46:40)
	at C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:17:23
	at Generator.next (<anonymous>)
	at C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:7:65
	at Promise (<anonymous>)
	at __awaiter (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:3:12)
	at activate (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:15:12)
	at Function.e._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:423087)
	at Function.e._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422832)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422185
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:41309)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:44874)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46702)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46143)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49638)
	at G.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49852)
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:41309)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:44874)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46702)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46143)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49638)
	at G.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49852)
e.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] Detecting environment: Visual Studio Community 2017 - arm
extensionHost.ts:384 [Extension Host] Error running C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat ERROR: Invalid host architecture 'arm'.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***

extensionHost.ts:384 [Extension Host] Environments loaded
extensionHost.ts:384 [Extension Host] Detected available environment "Visual Studio Community 2017 - x86
extensionHost.ts:384 [Extension Host] Detected available environment "Visual Studio Community 2017 - amd64
extensionHost.ts:384 [Extension Host] Started new CMake Server instance with PID 2432
extensionHost.ts:384 [Extension Host] Received message from cmake-server: 
{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":0}],"type":"hello"}

extensionHost.ts:384 [Extension Host] Trying to detect generator supported by system
extensionHost.ts:384 [Extension Host] Build program for generator Ninja is not found. Skipping...
extensionHost.ts:384 [Extension Host] Build program for generator Unix Makefiles is not found. Skipping...
extensionHost.ts:384 [Extension Host] None of preferred generators available on the system.
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionHost.ts:384 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed: Unable to determine CMake Generator to use.
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionHost.ts:384 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed:  Unable to determine CMake Generator to use
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionService.ts:405 Activating extension `vector-of-bool.cmake-tools` failed: Unable to determine CMake Generator to use.
e._logMessageInConsole @ extensionService.ts:405
e._logOrShowMessage @ extensionService.ts:419
e.$localShowMessage @ mainThreadExtensionService.ts:31
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionService.ts:405 Extension `maddouri.cmake-tools-helper` failed to activate. Reason: dependency `vector-of-bool.cmake-tools` failed to activate.
e._logMessageInConsole @ extensionService.ts:405
e._logOrShowMessage @ extensionService.ts:419
e.$localShowMessage @ mainThreadExtensionService.ts:31
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] Here is the error stack:  Error: Unable to determine CMake Generator to use
	at Function.<anonymous> (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\server-client.js:268:43)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\server-client.js:4:58)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)
extensionHost.ts:384 [Extension Host] Extension `maddouri.cmake-tools-helper` failed to activate. Reason: dependency `vector-of-bool.cmake-tools` failed to activate.
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionHost.ts:384 [Extension Host] rejected promise not handled within 1 second
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
shell.ts:419 [vector-of-bool.cmake-tools] Unable to determine CMake Generator to use: Error: Unable to determine CMake Generator to use
	at Function.<anonymous> (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\server-client.js:268:43)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\server-client.js:4:58)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)
e.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] Sync : Connected with user : 'jas99'
2extensionHost.ts:384 [Extension Host] Error: socket hang up
	at module.exports.sendError (C:\Users\jas\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:854:19)
	at C:\Users\jas\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:865:29
	at callCallback (C:\Users\jas\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:728:17)
	at ClientRequest.<anonymous> (C:\Users\jas\.vscode\extensions\Shan.code-settings-sync-2.8.3\node_modules\github\lib\index.js:807:17)
	at emitOne (events.js:96:13)
	at ClientRequest.emit (events.js:191:7)
	at TLSSocket.socketOnEnd (_http_client.js:394:9)
	at emitNone (events.js:91:20)
	at TLSSocket.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionHost.ts:384 [Extension Host] (node:11020) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by vector-of-bool** [comment]
Thanks for including the full event log. It provides some insight.

As further testing, can you try the following and report back the results:

1. Try deleting the `.cmaketools.json` file from `.vscode` for your project(s).
2. Try deleting `CMakeCache.txt` and `CMakeFiles` from your build directory.
3. Try disabling cmake-server in your `settings.json`.

Also, you mention running VSCode from a dev command prompt. Does the issue appear both inside and outside such an environment?

**Comment by jas99** [comment]
`1.Try deleting the .cmaketools.json file from .vscode for your project(s).`
`2. Try deleting CMakeCache.txt and CMakeFiles from your build directory.`
Already tried both of these steps before reporting this and issue still thr.

`
Also, you mention running VSCode from a dev command prompt. Does the issue appear both inside and outside such an environment?`
Yes issue is occurs in both cases

**Comment by jas99** [comment]
`3. Try disabling cmake-server in your settings.json.`

After disabling get following event log.
```
[Extension Host] Starting CMake Tools backend
extensionHost.ts:384 [Extension Host] [cmake output]: cmake version 3.9.3
extensionHost.ts:384 [Extension Host] [cmake output]: 
extensionHost.ts:384 [Extension Host] [cmake output]: CMake suite maintained and supported by Kitware (kitware.com/cmake).
extensionHost.ts:384 [Extension Host] cmake exited with return code 0
extensionHost.ts:384 [Extension Host] Loading environments
extensionHost.ts:384 [Extension Host] Loading CMake Tools from d:\repo\gitlab.com\computervision\temp\.vscode\.cmaketools.json
extensionHost.ts:384 [Extension Host] Detecting environment: Visual Studio Community 2017 - x86
extensionHost.ts:384 [Extension Host] Detecting environment: Visual Studio Community 2017 - amd64
extensionHost.ts:384 [Extension Host] Detecting environment: Visual Studio Community 2017 - arm
extensionHost.ts:384 [Extension Host] Found all parseable documents.
extensionHost.ts:384 [Extension Host] Parsing documents and looking for CSS class definitions...
extensionHost.ts:384 [Extension Host] Summary:
extensionHost.ts:384 [Extension Host] 0 parseable documents found
extensionHost.ts:384 [Extension Host] 0 CSS class definitions found
extensionHost.ts:384 [Extension Host] 0 unique CSS class definitions found
extensionHost.ts:384 [Extension Host] 0 failed attempts to parse. List of the documents:
extensionHost.ts:384 [Extension Host] 
shell.ts:419 [ms-vscode.cpptools] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at vscode.window.onDidChangeTextEditorSelection (C:\Users\jas\.vscode\extensions\ms-vscode.cpptools-0.13.0\out\src\LanguageServer\C_Cpp.js:145:97)
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:55287)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57078)
	at e.$acceptSelectionsChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:394527)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:423958)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:280554)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:280244)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:279271
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:281190
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:56058
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:55287)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57078)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:102495)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] rejected promise not handled within 1 second
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
shell.ts:419 [vector-of-bool.cmake-tools] Invalid backend promise: Error: Invalid backend promise
	at new CMakeToolsWrapper (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\wrapper.js:46:40)
	at C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:17:23
	at Generator.next (<anonymous>)
	at C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:7:65
	at Promise (<anonymous>)
	at __awaiter (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:3:12)
	at activate (C:\Users\jas\.vscode\extensions\vector-of-bool.cmake-tools-0.10.2\out\src\extension.js:15:12)
	at Function.e._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:423087)
	at Function.e._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422832)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422185
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:41309)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:44874)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46702)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46143)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49638)
	at G.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49852)
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:41309)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:44874)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46702)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46143)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49638)
	at G.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:49852)
e.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] Error running C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat ERROR: Invalid host architecture 'arm'.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***

extensionHost.ts:384 [Extension Host] Environments loaded
extensionHost.ts:384 [Extension Host] Detected available environment "Visual Studio Community 2017 - x86
extensionHost.ts:384 [Extension Host] Detected available environment "Visual Studio Community 2017 - amd64
extensionHost.ts:384 [Extension Host] Please set 'cmake.useCMakeServer' to 'true'
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionHost.ts:384 [Extension Host] cmake-tools-helper.cmake_download_path:C:\Users\jas\.vscode\extensions\maddouri.cmake-tools-helper-0.1.1\cmake_download
messageService.ts:125 Please set 'cmake.useCMakeServer' to 'true'
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e._showMessage @ mainThreadMessageService.ts:72
n.Class.derive._oncancel @ winjs.base.raw.js:1641
e._showMessage @ mainThreadMessageService.ts:42
e.$showMessage @ mainThreadMessageService.ts:36
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] Pass: Writing the active config
extensionHost.ts:384 [Extension Host] Sync : Connected with user : 'jas99'
```

**Comment by jas99** [comment]
Feel free to ask for more tests.
Thx

**Comment by vector-of-bool** [comment]
Sorry for the delay. I'm working on a large refactoring.

It looks to be something wrong with handling the vs environment detection. Did you happen to add/remove ARM toolchains?

**Comment by jas99** [comment]
Nope didn't add/removed ARM toolchaines

**Comment by LeonineKing1199** [comment]
I have this same issue as well. Just happened overnight for me.

**Comment by vitalyster** [comment]
+1

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by FelikZ** [comment]
I had this problem after changed `"cmake.generator": "Unix Makefiles"`.
"Reload window" helped me.
