### ISSUE TITLE
Hangs on "Configuring using the "MinGW Makefiles" CMake generator"

### ISSUE THREAD

**Issue by Oliv4945** [vector-of-bool/vscode-cmake-tools#259]
Hi,

I am trying to settup a CMake project under VS Code thanks to your extension, but it seems to hang.
At startup I have the following log:
```
Starting CMake Tools backend
[C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe output]: cmake version 3.10.0-rc5
[C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe output]: 
[C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe output]: CMake suite maintained and supported by Kitware (kitware.com/cmake).
C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe exited with return code 0
Loading CMake Tools from c:\Users\oooo\Documents\Projets\Tools\test-cmake-mig\.vscode\.cmaketools.json
VSWhere is not installed. Not searching for VS 2017
Detected available environment "MinGW - C:\MinGW
Started new CMake Server instance with PID 5148
Trying to detect generator supported by system
[vscode] Configuring using the "MinGW Makefiles" CMake generator
```

Then it stops, I cannot do things like "CMake: configure", nothing happens.

Following is the log from "Developer tools" with two unexpected exception, I do not now if it is relevant.
Thank you for your help !

Oliv'
```
console.ts:123 [Extension Host] Starting CMake Tools backend
console.ts:123 [Extension Host] [C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe output]: cmake version 3.10.0-rc5
console.ts:123 [Extension Host] [C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe output]: 
console.ts:123 [Extension Host] [C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe output]: CMake suite maintained and supported by Kitware (kitware.com/cmake).
console.ts:123 [Extension Host] C:\Users\oooo\Documents\Projets\Tools\cmake-3.10.0-rc5-win64-x64\bin\cmake.exe exited with return code 0
console.ts:123 [Extension Host] Loading environments
console.ts:123 [Extension Host] Loading CMake Tools from c:\Users\oooo\Documents\Projets\Tools\test-cmake-mig\.vscode\.cmaketools.json
console.ts:123 [Extension Host] VSWhere is not installed. Not searching for VS 2017
console.ts:123 [Extension Host] Environments loaded
console.ts:123 [Extension Host] Detected available environment "MinGW - C:\MinGW
console.ts:123 [Extension Host] Started new CMake Server instance with PID 4784
console.ts:123 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:123
shell.ts:459 [vector-of-bool.cmake-tools] Invalid backend promise: Error: Invalid backend promise
	at new CMakeToolsWrapper (C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\wrapper.js:46:40)
	at C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\extension.js:17:23
	at Generator.next (<anonymous>)
	at C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\extension.js:7:65
	at Promise (<anonymous>)
	at __awaiter (C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\extension.js:3:12)
	at activate (C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\extension.js:15:12)
	at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:505706)
	at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:505451)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:504804
e.onUnexpectedError @ shell.ts:459
console.ts:123 [Extension Host] Received message from cmake-server: 
{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":1}],"type":"hello"}

console.ts:123 [Extension Host] Trying to detect generator supported by system
console.ts:123 [Extension Host] [vscode] Configuring using the "MinGW Makefiles" CMake generator
console.ts:123 [Extension Host] Sending message to cmake-server: {"type":"handshake","buildDirectory":"c:/users/oooo/documents/projets/tools/test-cmake-mig/build","protocolVersion":{"isExperimental":true,"major":1,"minor":1},"sourceDirectory":"c:/users/oooo/documents/projets/tools/test-cmake-mig","generator":"MinGW Makefiles","cookie":"0.9213053386548808"}
console.ts:123 [Extension Host] Received message from cmake-server: 
{"cookie":"0.9213053386548808","inReplyTo":"handshake","type":"reply"}

console.ts:123 [Extension Host] Sending message to cmake-server: {"type":"globalSettings","cookie":"0.9378025195711566"}
console.ts:123 [Extension Host] Received message from cmake-server: 
{"buildDirectory":"c:/users/oooo/documents/projets/tools/test-cmake-mig/build","capabilities":{"generators":[{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"Ninja","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 15 2017","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 15 2017 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 12 2013","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Borland Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 15 2017 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 9 2008","platformSupport":true,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 12 2013 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 10 2010 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 12 2013 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 14 2015","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 11 2012 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 14 2015 ARM","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 14 2015 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 11 2012","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 9 2008 Win64","platformSupport":true,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 11 2012 Win64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 10 2010","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 10 2010 IA64","platformSupport":true,"toolsetSupport":true},{"extraGenerators":[],"name":"Visual Studio 9 2008 IA64","platformSupport":true,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 8 2005","platformSupport":true,"toolsetSupport":false},{"extraGenerators":[],"name":"MSYS Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Visual Studio 8 2005 Win64","platformSupport":true,"toolsetSupport":false},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"NMake Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Watcom WMake","platformSupport":false,"toolsetSupport":false},{"extraGenerators":["CodeBlocks"],"name":"NMake Makefiles JOM","platformSupport":false,"toolsetSupport":false},{"extraGenerators":[],"name":"Green Hills MULTI","platformSupport":false,"toolsetSupport":false},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"MinGW Makefiles","platformSupport":false,"toolsetSupport":false},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"Unix Makefiles","platformSupport":false,"toolsetSupport":false}],"serverMode":true,"version":{"isDirty":false,"major":3,"minor":10,"patch":0,"string":"3.10.0-rc5","suffix":"rc5"}},"checkSystemVars":false,"cookie":"0.9378025195711566","debugOutput":false,"extraGenerator":"","generator":"MinGW Makefiles","inReplyTo":"globalSettings","sourceDirectory":"c:/users/oooo/documents/projets/tools/test-cmake-mig","trace":false,"traceExpand":false,"type":"reply","warnUninitialized":false,"warnUnused":false,"warnUnusedCli":true}

console.ts:123 [Extension Host] Sending message to cmake-server: {"type":"cache","cookie":"0.513476075508333"}
console.ts:123 [Extension Host] Sending message to cmake-server: {"type":"codemodel","cookie":"0.35857727376603754"}
console.ts:123 [Extension Host] Received message from cmake-server: 
{"cookie":"","errorMessage":"Failed to parse JSON input.","inReplyTo":"","type":"error"}

shell.ts:459 [vector-of-bool.cmake-tools] Invalid cookie: : Error: Invalid cookie: 
	at CMakeServerClient._takePromiseForCookie (C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\server-client.js:112:19)
	at CMakeServerClient._onMessage (C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\server-client.js:128:26)
	at CMakeServerClient._onMoreData (C:\Users\oooo\.vscode\extensions\vector-of-bool.cmake-tools-0.10.3\out\src\server-client.js:105:18)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.onUnexpectedError @ shell.ts:459

```

**Comment by vector-of-bool** [comment]
Looks like it might be related to #237.

**Comment by Oliv4945** [comment]
A downgrade from CMake 3.10-rc-5 to 3.8 seems to solve it, I will try with 3.9
I don't know if you want to close the issue as the plugin does not seems to be able to handle the error

**Comment by vector-of-bool** [comment]
Looks to be the same #258. This must be a problem with CMake 3.10

**Comment by vector-of-bool** [comment]
Closing this and moving to the other issue.

**Comment by vector-of-bool** [comment]
Should all work in the 3.10 release.
