### ISSUE TITLE
0.11.0 beta 1 and 2: commands not registered on macOS

### ISSUE THREAD

**Issue by sterin** [vector-of-bool/vscode-cmake-tools#278]
### Brief Issue Summary

Any attempt to run a cmake-tools command results with an error message similar to:

> Error: command 'cmake.setVariant' not found

### CMake Tools Log

```
[variant] Loaded new set of variants
[kit] Failed to check binary /usr/bin/clang by exception: Error: spawn stdbuf ENOENT
[kit] Failed to check binary /usr/bin/gcc by exception: Error: spawn stdbuf ENOENT
[kit] Failed to check binary /usr/local/bin/gcc-7 by exception: Error: spawn stdbuf ENOENT
```

### Developer Tools Log

```
[Extension Host] debugger listening on port 9333
extensionHost.ts:200 [Extension Host] debugger inspector at %cDebugger listening on port 9333.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9333/59759204-b550-446c-8e05-fb920a169b7a

extensionService.ts:656 [/Users/sterin/.vscode/extensions/ms-vscode.cpptools-0.14.5]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
extensionService.ts:656 [/Users/sterin/.vscode/extensions/ms-vscode.cpptools-0.14.5]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.045Z [debug] [main] Safe constructing new CMakeTools instance
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.047Z [debug] [kit] Constructing KitManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.047Z [debug] [variant] Constructing VariantManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.049Z [debug] [main] Constructing new CMakeTools instance
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.050Z [debug] [main] Starting CMakeTools second-phase init
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.051Z [debug] [rollbar] Checking Rollbar permissions
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.051Z [debug] [rollbar] Rollbar enabled?  true
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.123Z [info] [variant] Loaded new set of variants
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.126Z [debug] [kit] Second phase init for KitManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.127Z [debug] [kit] Rescanning for Kits
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.129Z [debug] [kit] Scanning for Kits on system
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.131Z [debug] [kit] Scanning directory /Users/sterin/.local/bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.131Z [debug] [kit] Scanning directory /usr/local/bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.131Z [debug] [kit] Scanning directory /usr/bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.131Z [debug] [kit] Scanning directory /bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.132Z [debug] [kit] Scanning directory /usr/sbin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.132Z [debug] [kit] Scanning directory /sbin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.132Z [debug] [kit] Scanning directory /opt/X11/bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.132Z [debug] [kit] Scanning directory /Developer/Panda3D/bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.132Z [debug] [kit] Scanning directory /Library/Frameworks/Mono.framework/Versions/Current/Commands for compilers
console.ts:123 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed: spawn stdbuf ENOENT.
t.log @ console.ts:123
console.ts:123 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed:  spawn stdbuf ENOENT
t.log @ console.ts:123
console.ts:123 [Extension Host] Here is the error stack:  Error: spawn stdbuf ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
extensionService.ts:652 Activating extension `vector-of-bool.cmake-tools` failed: spawn stdbuf ENOENT.
t._logMessageInConsole @ extensionService.ts:652
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.234Z [debug] [kit] Found 0 kits in directory /Users/sterin/.local/bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.252Z [debug] [kit] Found 0 kits in directory /bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.280Z [debug] [kit] Found 0 kits in directory /sbin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.306Z [debug] [kit] Testing Clang-ish binary: /usr/bin/clang
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.344Z [debug] [kit] Testing GCC-ish binary: /usr/bin/gcc
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.490Z [warning] [kit] Failed to check binary /usr/bin/clang by exception: Error: spawn stdbuf ENOENT
t.log @ console.ts:123
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.491Z [warning] [kit] Failed to check binary /usr/bin/gcc by exception: Error: spawn stdbuf ENOENT
t.log @ console.ts:123
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.532Z [debug] [kit] Found 0 kits in directory /usr/sbin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.556Z [debug] [kit] Found 0 kits in directory /opt/X11/bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.572Z [debug] [kit] Found 0 kits in directory /Developer/Panda3D/bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.590Z [debug] [kit] Found 0 kits in directory /Library/Frameworks/Mono.framework/Versions/Current/Commands
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.618Z [debug] [kit] Testing GCC-ish binary: /usr/local/bin/gcc-7
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T04:28:51.718Z [warning] [kit] Failed to check binary /usr/local/bin/gcc-7 by exception: Error: spawn stdbuf ENOENT
t.log @ console.ts:123
console.ts:123 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:123
mainThreadExtensionService.ts:43 [vector-of-bool.cmake-tools]Accessing CMake driver too early!
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
mainThreadExtensionService.ts:44 Error: Accessing CMake driver too early!
	at new CMakeTools (/Users/sterin/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta2/out/src/cmake-tools.js:75:44)
	at Function.create (/Users/sterin/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta2/out/src/cmake-tools.js:284:22)
	at activate (/Users/sterin/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta2/out/src/extension.js:24:45)
	at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:512:370)
	at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:512:54)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:511:329
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:67:449)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:70:778)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:573)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:14)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
```

### Platform and Versions

- **Operating System**: macOS (High Sierra)
- **CMake Version**: 3.9.4
- **VSCode Version**: 1.19.1
- **CMake Tools Extension Version**: 0.11.0 beta 2
- **Compiler/Toolchain**: Apple clang

**Comment by vector-of-bool** [comment]
Eh... I see the problem. It's trying to run `stdbuf`, but macOS doesn't seem to have that?

**Comment by sterin** [comment]
It doesn't have stdbuf by default.

I installed stdbuf using Homebrew (part of the coreutils package) and added into PATH to test it and it seems to work now.

**Comment by vector-of-bool** [comment]
Should be fixed in next (beta?) release
