### ISSUE TITLE
Start of extension fails with state of incompatible variant

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#279]
### Brief Issue Summary

On testing the new beta on my windows PC I can not use the extension.
The developer mode shows a exception "Unexpected missing variant setting.".
In my last loaded project I used a other variant file then in the new project.

### Expected:

I have to exceptions:
1. The extension should always be accessible, so that I can reset the internal state for troubleshooting or reset/edit the kit selection.
2. The extension should fix a invalid internal history state without user interaction.

### Apparent Behavior:

1. Open project with variant configuration
2. select a variant
3. close project
4. open project with different variant configuration or edit variant configuration of present project  before opening
5. --> extension get exception

### Developer Tools Log

```
console.ts:123 [Extension Host] activating extension
console.ts:123 [Extension Host] starting language server
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.305Z [debug] [main] Safe constructing new CMakeTools instance
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.306Z [debug] [kit] Constructing KitManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.307Z [debug] [variant] Constructing VariantManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.309Z [debug] [main] Constructing new CMakeTools instance
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.310Z [debug] [main] Starting CMakeTools second-phase init
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.310Z [debug] [rollbar] Checking Rollbar permissions
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.310Z [debug] [rollbar] Rollbar enabled?  false
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T07:05:25.347Z [info] [variant] Loaded new set of variants
console.ts:123 [Extension Host] Fehler beim Aktivieren der Extension "vector-of-bool.cmake-tools": Unexpected missing variant setting.
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:123 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed:  Unexpected missing variant setting
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:123 [Extension Host] Here is the error stack:  Error: Unexpected missing variant setting
	at __dirname.activeVariantOptions.Array.from.map (C:\Users\mmairbaeur\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\variant.js:181:23)
	at Array.map (native)
	at VariantManager.get activeVariantOptions [as activeVariantOptions] (C:\Users\mmairbaeur\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\variant.js:178:48)
	at CMakeTools._init (C:\Users\mmairbaeur\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\cmake-tools.js:233:63)
	at <anonymous>
extensionService.ts:652 Fehler beim Aktivieren der Extension "vector-of-bool.cmake-tools": Unexpected missing variant setting.
t._logMessageInConsole @ extensionService.ts:652
t._logOrShowMessage @ extensionService.ts:666
e.$localShowMessage @ mainThreadExtensionService.ts:32
e.invoke @ abstractThreadService.ts:42
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:126 command 'cmake.scanForKits' not found
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
t.onError @ commandsHandler.ts:289
(anonymous) @ commandsHandler.ts:325
done @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
e.resolveOk @ lazyPromise.ts:65
e._receiveOneMessage @ rpcProtocol.ts:72
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:123 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
mainThreadExtensionService.ts:43 [vector-of-bool.cmake-tools]Accessing CMake driver too early!
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e.invoke @ abstractThreadService.ts:42
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 Error: Accessing CMake driver too early!
	at new CMakeTools (C:\Users\mmairbaeur\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\cmake-tools.js:75:44)
	at Function.create (C:\Users\mmairbaeur\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\cmake-tools.js:284:22)
	at activate (C:\Users\mmairbaeur\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\extension.js:24:45)
	at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:370)
	at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:54)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:511:329
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:67:449)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:70:778)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:573)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:14)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e.invoke @ abstractThreadService.ts:42
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:126 command 'cmake.scanForKits' not found
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e.resume @ messageService.ts:64
(anonymous) @ workbench.ts:1024
e.fire @ event.ts:142
(anonymous) @ quickOpenController.ts:535
messageService.ts:126 command 'cmake.resetState' not found
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e.resume @ messageService.ts:64
(anonymous) @ workbench.ts:1024
e.fire @ event.ts:142
(anonymous) @ quickOpenController.ts:535
messageService.ts:126 Die Erweiterung "CMake Tools" kann nicht deaktiviert werden. Die Erweiterung "CMake Tools Helper" ist davon abhängig.: Error: Die Erweiterung "CMake Tools" kann nicht deaktiviert werden. Die Erweiterung "CMake Tools Helper" ist davon abhängig.
    at e.checkAndSetEnablement (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3347:170)
    at e.promptAndSetEnablement (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3346:321)
    at e.setEnablement (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3345:736)
    at t.run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4151:506)
    at e.runAction (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:176:11)
    at e.run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:175:843)
    at e.runAction (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2554:956)
    at click (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2554:496)
    at CallbacksRegistry.apply (C:\Program Files\Microsoft VS Code\resources\electron.asar\common\api\callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (C:\Program Files\Microsoft VS Code\resources\electron.asar\renderer\api\remote.js:299:21)
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ extensionsList.ts:91
e.fire @ event.ts:142
(anonymous) @ actionbar.ts:399
e.fire @ event.ts:142
(anonymous) @ actions.ts:221
then @ winjs.base.raw.js:1436
e.run @ actions.ts:218
e.runAction @ contextmenuService.ts:123
click @ contextmenuService.ts:87
apply @ C:\Program Files\Microsoft VS Code\resources\electron.asar\common\api\callbacks-registry.js:48
(anonymous) @ C:\Program Files\Microsoft VS Code\resources\electron.asar\renderer\api\remote.js:299
emitThree @ events.js:116
emit @ events.js:197
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.9
- **VSCode Version**: 1.19
- **CMake Tools Extension Version**: 0.11/beta2
- **Compiler/Toolchain**: not needed this problem

**Comment by vector-of-bool** [comment]
Will be fixed in next release
