### ISSUE TITLE
0.11.0-beta2 cannot light up

### ISSUE THREAD

**Issue by MathiasMagnus** [vector-of-bool/vscode-cmake-tools#283]
### Brief Issue Summary

The majority of the extensions features are not available, because it cannot initialize

### Expected:

A working extension

### Apparent Behavior:

Just about every extension feature throws errors

### CMake Tools Log

Where are these?

### Developer Tools Log

```
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.635Z [debug] [main] Safe constructing new CMakeTools instance
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.636Z [debug] [kit] Constructing KitManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.636Z [debug] [variant] Constructing VariantManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.638Z [debug] [main] Constructing new CMakeTools instance
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.640Z [debug] [main] Starting CMakeTools second-phase init
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.640Z [debug] [rollbar] Checking Rollbar permissions
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.641Z [debug] [rollbar] Rollbar enabled?  true
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.770Z [info] [variant] Loaded new set of variants
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.773Z [debug] [kit] Second phase init for KitManager
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.774Z [debug] [kit] Rescanning for Kits
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.774Z [debug] [kit] Scanning for Kits on system
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.774Z [debug] [kit] Scanning directory C:\Python36\Scripts\ for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.775Z [debug] [kit] Scanning directory C:\Python36\ for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.775Z [debug] [kit] Scanning directory C:\Kellekek\Microsoft\MPI\8.1\Bin\ for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.775Z [debug] [kit] Scanning directory C:\WINDOWS\system32 for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.775Z [debug] [kit] Scanning directory C:\WINDOWS for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.775Z [debug] [kit] Scanning directory C:\WINDOWS\System32\Wbem for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.776Z [debug] [kit] Scanning directory C:\WINDOWS\System32\WindowsPowerShell\v1.0\ for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.776Z [debug] [kit] Scanning directory C:\ProgramData\chocolatey\bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.776Z [debug] [kit] Scanning directory C:\Program Files (x86)\vim\vim80 for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.776Z [debug] [kit] Scanning directory C:\Program Files\OpenSSH-Win64 for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.776Z [debug] [kit] Scanning directory C:\Program Files\Git\cmd for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.777Z [debug] [kit] Scanning directory C:\Kellekek\Microsoft\MPI\8.1\Bin\ for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.777Z [debug] [kit] Scanning directory C:\Kellekek\AMD\clFFT\2.12\bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.777Z [debug] [kit] Scanning directory C:\Kellekek\AMD\clBLAS\2.12\bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.777Z [debug] [kit] Scanning directory C:\Kellekek\Qt\5.9.2\5.9.2\msvc2017_64\bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.778Z [debug] [kit] Scanning directory C:\Kellekek\Codeplay\ComputeCpp\0.5.0\bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.778Z [debug] [kit] Scanning directory C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.778Z [debug] [kit] Scanning directory  for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.779Z [debug] [kit] Scanning directory C:\Kellekek\Microsoft\Visual Studio\Code\bin for compilers
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.786Z [warning] [kit] Failed to scan  by exception: Error: ENOENT: no such file or directory, stat ''
t.log @ console.ts:123
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.788Z [debug] [kit] Found 0 kits in directory C:\Python36\Scripts\
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.796Z [debug] [kit] Found 0 kits in directory C:\Python36\
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.797Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Microsoft\MPI\8.1\Bin\
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.839Z [debug] [kit] Found 0 kits in directory C:\WINDOWS
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.848Z [debug] [kit] Found 0 kits in directory C:\WINDOWS\System32\WindowsPowerShell\v1.0\
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.853Z [debug] [kit] Found 0 kits in directory C:\ProgramData\chocolatey\bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.918Z [debug] [kit] Found 0 kits in directory C:\WINDOWS\System32\Wbem
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.929Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\vim\vim80
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.933Z [debug] [kit] Found 0 kits in directory C:\Program Files\OpenSSH-Win64
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.934Z [debug] [kit] Found 0 kits in directory C:\Program Files\Git\cmd
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.935Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Microsoft\MPI\8.1\Bin\
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.936Z [debug] [kit] Found 0 kits in directory C:\Kellekek\AMD\clFFT\2.12\bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.936Z [debug] [kit] Found 0 kits in directory C:\Kellekek\AMD\clBLAS\2.12\bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.966Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Qt\5.9.2\5.9.2\msvc2017_64\bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.967Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Codeplay\ComputeCpp\0.5.0\bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.968Z [debug] [kit] Testing Clang-ish binary: C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.970Z [warning] [kit] Failed to check binary C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang by exception: Error: spawn C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang ENOENT
t.log @ console.ts:123
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:15.972Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Microsoft\Visual Studio\Code\bin
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.746Z [debug] [kit] Found 0 kits in directory C:\WINDOWS\system32
mainThreadExtensionService.ts:44 Error: Accessing CMake driver too early!
	at new CMakeTools (C:\Users\nagy-\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\cmake-tools.js:75:44)
	at Function.create (C:\Users\nagy-\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\cmake-tools.js:284:22)
	at activate (C:\Users\nagy-\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\extension.js:24:45)
	at Function.t._callActivateOptional (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:370)
	at Function.t._callActivate (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:54)
	at c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:511:329
	at Object.g [as _notify] (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:67:449)
	at Object.enter (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:70:778)
	at n.Class.derive._oncancel._run (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:573)
	at n.Class.derive._oncancel._completed (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:14)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.776Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - x86
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.777Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - amd64
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.777Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - x86_amd64
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.777Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - x86_arm
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.778Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - amd64_arm
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.778Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - amd64_x86
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.782Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.4989049025645884.bat
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.785Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.24963561786755872.bat
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.787Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.8527074592246469.bat
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.790Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.7951915583820284.bat
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.792Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.01855731831629348.bat
console.ts:123 [Extension Host] [CMakeTools] 2017-12-21T14:52:16.795Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.3047038843842753.bat

```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.10.0
- **VSCode Version**: 1.19.1
- **CMake Tools Extension Version**: 0.11.0-beta2
- **Compiler/Toolchain**: Visual C++ 2017 (Build Tools ONLY, 15.5.2)

### Other Notes/Information

Nothing yet.

**Comment by vector-of-bool** [comment]
Possibly startup hasn't finished yet. If you give it two or three minutes to start, do you still see the error? I need to fix it so that kit scanning doesn't block everything.

**Comment by MathiasMagnus** [comment]
No, waiting 10 minutes on an 8C/16T beast is definitely not a time related issue.

I checked again, and found another error that was filtered out the last time and is related to one of the kit checks throwing a hard error which in turn seems to wreck the entire process.

The relevant error is near the top. I got [ComputeCpp](https://www.codeplay.com/products/computesuite/computecpp) installed (the first and only GPU-accelerated SYCL implementation to date) which is a Clang fork. It is a Clang fork that generates OpenCL SPIR(-V) code to be executed on the device, but mistaking it for a host-side Clang compiler can break things. Even if it can create functioning x86 binaries, it is not meant to do so.

The ENOENT error seems to stem from `C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang` which is a valid path, but is a folder, not an exe. It is in the PATH because there are DLLs in the lib directory, and also a folder named clang. I suspect CMake Tools mistakes it for a binary and tries to invoke it.

```
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:39.883Z [debug] [kit] Found 0 kits in directory C:\Kellekek\AMD\clFFT\2.12\bin
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:39.883Z [debug] [kit] Found 0 kits in directory C:\Kellekek\AMD\clBLAS\2.12\bin
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:39.884Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Codeplay\ComputeCpp\0.5.0\bin
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:39.885Z [debug] [kit] Testing Clang-ish binary: C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:39.887Z [warning] [kit] Failed to check binary C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang by exception: Error: spawn C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang ENOENT
t.log @ /C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed: spawn C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang ENOENT.
t.log @ /C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed:  spawn C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang ENOENT
t.log @ /C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Here is the error stack:  Error: spawn C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:39.923Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Qt\5.9.2\5.9.2\msvc2017_64\bin
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:39.924Z [debug] [kit] Found 0 kits in directory C:\Kellekek\Microsoft\Visual Studio\Code\bin
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:4054 Activating extension `vector-of-bool.cmake-tools` failed: spawn C:\Kellekek\Codeplay\ComputeCpp\0.5.0\lib\clang ENOENT.
t._logMessageInConsole @ /C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:4054
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.750Z [debug] [kit] Found 0 kits in directory C:\WINDOWS\system32
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] rejected promise not handled within 1 second
t.log @ /C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:4056 [vector-of-bool.cmake-tools]Accessing CMake driver too early!
e.$onExtensionRuntimeError @ /C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:4056
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:4056 Error: Accessing CMake driver too early!
	at new CMakeTools (C:\Users\nagy-\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\cmake-tools.js:75:44)
	at Function.create (C:\Users\nagy-\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\cmake-tools.js:284:22)
	at activate (C:\Users\nagy-\.vscode\extensions\vector-of-bool.cmake-tools-0.11.0-beta2\out\src\extension.js:24:45)
	at Function.t._callActivateOptional (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:370)
	at Function.t._callActivate (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:54)
	at c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:511:329
	at Object.g [as _notify] (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:67:449)
	at Object.enter (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:70:778)
	at n.Class.derive._oncancel._run (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:573)
	at n.Class.derive._oncancel._completed (c:\Kellekek\Microsoft\Visual Studio\Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:14)
e.$onExtensionRuntimeError @ /C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:4056
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.782Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - x86
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.782Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - amd64
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.782Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - x86_amd64
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.783Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - x86_arm
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.783Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - amd64_arm
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.783Z [debug] [kit] Checking for kit: Visual Studio Build Tools 2017 - amd64_x86
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.791Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.0784794933349442.bat
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.796Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.4623396889718321.bat
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.800Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.7739118264513238.bat
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.805Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.2659411450688227.bat
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.810Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.05618894665623175.bat
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] [CMakeTools] 2017-12-22T12:09:40.816Z [info] [proc] Executing command: C:\Users\nagy-\AppData\Local\Temp\vs-cmt-0.4864995803186891.bat
/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Error running C:\Kellekek\Microsoft\Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat ERROR: Invalid host architecture 'amd64_arm'.
[ERROR:winsdk.bat] Host architecture is not valid : 'amd64_arm'
[ERROR:vcvars.bat] Unknown host architecture 'amd64_arm'
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***

/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Error running C:\Kellekek\Microsoft\Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat ERROR: Invalid host architecture 'x86_amd64'.
[ERROR:winsdk.bat] Host architecture is not valid : 'x86_amd64'
[ERROR:vcvars.bat] Unknown host architecture 'x86_amd64'
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***

/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Error running C:\Kellekek\Microsoft\Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat ERROR: Invalid host architecture 'x86_arm'.
[ERROR:winsdk.bat] Host architecture is not valid : 'x86_arm'
[ERROR:vcvars.bat] Unknown host architecture 'x86_arm'
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***

/C:/Kellekek/Microsoft/Visual Studio/Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Error running C:\Kellekek\Microsoft\Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat ERROR: Invalid host architecture 'amd64_x86'.
[ERROR:winsdk.bat] Host architecture is not valid : 'amd64_x86'
[ERROR:vcvars.bat] Unknown host architecture 'amd64_x86'
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
```

**Comment by vector-of-bool** [comment]
Nice find! I just pushed out a potential fix in beta3.

**Comment by vector-of-bool** [comment]
Reopen if you still experience problems.
