### ISSUE TITLE
macOS: After installation -> Spawn Error

### ISSUE THREAD

**Issue by gabyx** [vector-of-bool/vscode-cmake-tools#294]
Install the extension beta 4.
 
-> Scan for Kits:

Spawn Error:

[Cmake.log](https://github.com/vector-of-bool/vscode-cmake-tools/files/1600035/Cmake.log)

in Output Pane:
[variant] Loaded new set of variants
[rollbar] Unhandled exception: Unhandled Promise rejection: scanForKits Error: spawn EACCES {}

**Comment by spoosanthiram** [comment]
I am getting same error, here is the log:
[2018-02-04 18:21:28.302] [renderer1] [error] spawn EACCES: Error: spawn EACCES
        at exports._errnoException (util.js:1050:11)
        at ChildProcess.spawn (internal/child_process.js:319:11)
        at Object.exports.spawn (child_process.js:390:9)
        at Object.execute (/Users/saravanan/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta4/out/src/proc.js:48:22)
        at vsInstallations (/Users/saravanan/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta4/out/src/kit.js:173:36)
        at scanForVSKits (/Users/saravanan/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta4/out/src/kit.js:327:28)
        at vscode.window.withProgress (/Users/saravanan/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta4/out/src/kit.js:366:25)
        at e._withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:390:114)
        at e.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:389:975)
        at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:499:707)

On my Linux box, I don't see the error.

**Comment by spinicist** [comment]
I think I'm seeing this exact error as well. "Scan for Kits" causes the EACCES error, and where the kits should be listed I see "CMake: Unconfigured".

**Comment by vector-of-bool** [comment]
@KoeMai, you marked this as _Done_ for 0.11.0. Is this correct?

**Comment by KoeMai** [comment]
Yes since commit 2d10c61e1b5e244b832abd4faaebc467ecd52856.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
