### ISSUE TITLE
Doesn't initialize on a new installation on macOS

### ISSUE THREAD

**Issue by singalen** [vector-of-bool/vscode-cmake-tools#354]
### Brief Issue Summary

CMake project doesn't load.

I do have a CMakeLists.txt that works in CLion in the project root.

### Expected:

intelliSense works.

### Apparent Behavior:

1. Open a directory with CMakeLists.txt.
2. "Configure includePath for better IntelliSense results" appears.
3. In the status line I see: `CMake: Unconfigured  Project: Debug: Loading...    Build: `
4. When clicking a bug icon in the status bar, a popup appears: "spawn: EACCESS"
5. See console log below.

### CMake Tools Log

CMake/Build output panel doesn't exist.

### Developer Tools Log

```
[/Users/vic/.vscode/extensions/ms-vscode.cpptools-0.15.0]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
extensionService.ts:786 [/Users/vic/.vscode/extensions/ms-vscode.cpptools-0.15.0]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
console.ts:136 [Extension Host] [CMakeTools] 2018-03-23T20:37:46.957Z [debug] [main] Safe constructing new CMakeTools instance
console.ts:136 [Extension Host] [CMakeTools] 2018-03-23T20:37:46.962Z [debug] [kit] Constructing KitManager
console.ts:136 [Extension Host] [CMakeTools] 2018-03-23T20:37:46.964Z [debug] [variant] Constructing VariantManager
console.ts:136 [Extension Host] [CMakeTools] 2018-03-23T20:37:46.966Z [debug] [main] Constructing new CMakeTools instance
console.ts:136 [Extension Host] [CMakeTools] 2018-03-23T20:37:46.968Z [debug] [main] Starting CMakeTools second-phase init
console.ts:136 [Extension Host] [CMakeTools] 2018-03-23T20:37:46.968Z [debug] [rollbar] Checking Rollbar permissions
console.ts:136 [Extension Host] [CMakeTools] 2018-03-23T20:37:46.968Z [debug] [rollbar] Asking user for permission to user Rollbar...
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] starting language server
console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
mainThreadExtensionService.ts:43 [vector-of-bool.cmake-tools]Accessing CMake driver too early!
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
mainThreadExtensionService.ts:44 Error: Accessing CMake driver too early!
	at new CMakeTools (/Users/vic/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta4/out/src/cmake-tools.js:75:44)
	at Function.create (/Users/vic/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta4/out/src/cmake-tools.js:280:22)
	at activate (/Users/vic/.vscode/extensions/vector-of-bool.cmake-tools-0.11.0-beta4/out/src/extension.js:24:42)
	at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:695:93)
	at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:694:787)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:693:916
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:202)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:556)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:380)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:73:823)
```

### Platform and Versions

- **Operating System**: macOS 10.13
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.21.1
- **CMake Tools Extension Version**: 0.11b4
- **Compiler/Toolchain**: clang (Apple LLVM version 9.0.0 (clang-900.0.39.2))

### Other Notes/Information

Installed plugins:

twxs.cmake 0.0.17
maddouri.cmake-tools-helper 0.1.1
Harikrishnan.cmake-clangd-helper 0.1.0

**Comment by Randshot** [comment]
@singalen 
TBH, I don't really know what to think of this log output, but to me it seems like you didn't select an answer for the rollbar popup.
```ts
await rollbar.requestPermissions(this.extensionContext);
```
The extension waits for the user to select an option before continuing the initialization process.

**Comment by singalen** [comment]
Hm, I don't remember seeing such a popup for some reason.
Anyway, I think this one should be closed, I'll do a better job at reporting another time.

**Comment by Randshot** [comment]
Ok, I will close this issue then.
If you still encounter this issue, feel free to reopen this one or open another one.
