### ISSUE TITLE
Spawn ctest ENOENT

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#428]
Every time when I start an already configured CMake project (quickstart example) and click build or debug after load then I get the following error:

```
[CMakeTools] 2018-05-13T14:43:55.401Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: configure Error: spawn ctest ENOENT {}
logging.js:152
Error: spawn ctest ENOENT
rollbar.js:98
	at exports._errnoException (util.js:1050:11)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

# Platform and Versions

- Operating System: Windows 10
- CMake Version: 3.11
- VSCode Version: 1.23.0
- CMake Tools Extension Version: develop

**Comment by vector-of-bool** [comment]
@KoeMai try on develop with @physhh's changes. He may have fixed this one.

**Comment by vector-of-bool** [comment]
I'm going to close this, but re-open it if you still see this happening
