### ISSUE TITLE
Cannot use CMT build commands since 1.0.0

### ISSUE THREAD

**Issue by s-martin** [vector-of-bool/vscode-cmake-tools#454]
### Brief Issue Summary

All CMT build commands from the command palette fail

### Apparent Behavior:

On all build commands error 
`[rollbar] Unhandled exception: Unhandled Promise rejection: cleanConfigure TypeError: Cannot read property '1' of null {}`
occurred

### CMake Tools Log

```
[Extension Host] ApplicationInsights:Sender [Object]
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] [CMakeTools] 2018-06-07T08:47:23.945Z [debug] [extension] [5187] cmake.cleanConfigure started
console.ts:136 [Extension Host] [CMakeTools] 2018-06-07T08:47:23.946Z [debug] [main] Saving open files before configure/build
console.ts:136 [Extension Host] [CMakeTools] 2018-06-07T08:47:23.975Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: cleanConfigure TypeError: Cannot read property '1' of null {}
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] TypeError: Cannot read property '1' of null
	at Object.getCMakeExecutableInformation (/home/mts/.vscode/extensions/vector-of-bool.cmake-tools-1.0.0/out/src/cmake/cmake-executable.js:14:85)
	at <anonymous>
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
3dom.ts:175 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
browser.ts:163 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
notificationsAlerts.ts:39 Cannot read property '1' of null
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
t.onError @ commandsHandler.ts:326
(anonymous) @ commandsHandler.ts:311
done @ winjs.base.js:1393
v @ winjs.base.js:1239
enter @ winjs.base.js:916
_run @ winjs.base.js:1083
_error @ winjs.base.js:1056
e.resolveErr @ lazyPromise.ts:78
e._receiveReplyErr @ rpcProtocol.ts:245
e._receiveOneMessage @ rpcProtocol.ts:187
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
mainThreadExtensionService.ts:43 [vector-of-bool.cmake-tools]Cannot read property '1' of null
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 TypeError: Cannot read property '1' of null
	at Object.getCMakeExecutableInformation (/home/mts/.vscode/extensions/vector-of-bool.cmake-tools-1.0.0/out/src/cmake/cmake-executable.js:14:85)
	at <anonymous>
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

### Platform and Versions

[[For issues, fill out the following. Otherwise delete this section.]]

- **Operating System**: CentOS 7.5
- **CMake Version**: 3.11
- **VSCode Version**: 1.23.1
- **CMake Tools Version**: 1.0.0
- **Compiler/Toolchain**: GCC 7.2.1

**Comment by s-martin** [comment]
So commands selecting kits, resetting CMT etc. works, but no build related commands work

**Comment by vector-of-bool** [comment]
Looks to be barfing when it tries to parse the CMake version string. Could you paste the output of `cmake --version`?

**Comment by s-martin** [comment]
```
$ cmake3 --version
cmake3 version 3.11.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by s-martin** [comment]
Ok, I can confirm, if I'm using the cmake (version 2) command, it works.

Could you please add the possibility to use a executable called `cmake3`? AFAIR CMT doesn't really support CMake v2 anymore.

**Comment by vector-of-bool** [comment]
[Here it is](https://github.com/vector-of-bool/vscode-cmake-tools/blob/31587dd73c495af41c2e355ccc19e6512560cacb/src/cmake/cmake-executable.ts#L22). The regex expects the word `cmake` verbatim. Should be a simple fix.

**Comment by vector-of-bool** [comment]
Thanks for the PR! I'll get this out in 1.0.1

**Comment by s-martin** [comment]
Ok, works also in my production environments.

Thanks!
