### ISSUE TITLE
[not] Getting started: command 'cmake.quickStart' not found

### ISSUE THREAD

**Issue by gajop** [vector-of-bool/vscode-cmake-tools#467]
### Brief Issue Summary

Following the Getting Started guide, and choosing ` CMake: Quick Start` gives me the following:
`command 'cmake.quickStart' not found`

### Developer Tools Log

```
notificationsAlerts.ts:40 Error: command 'cmake.quickStart' not found
    at t._tryExecuteCommand (commandService.ts:57)
    at commandService.ts:50
    at n.Class.derive._oncancel.then (winjs.base.js:1581)
    at t.executeCommand (commandService.ts:50)
    at t.run (actions.ts:164)
    at t.run (actions.ts:202)
    at commandsHandler.ts:307
    at n.Class.derive._oncancel.done (winjs.base.js:1539)
    at Object.g [as _notify] (winjs.base.js:1195)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1083)
    at n.Class.derive._oncancel._completed (winjs.base.js:1051)
e.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
t.onError @ commandsHandler.ts:326
(anonymous) @ commandsHandler.ts:311
done @ winjs.base.js:1393
(anonymous) @ commandsHandler.ts:307
done @ winjs.base.js:1539
g @ winjs.base.js:1195
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.11.3 (separately installed system CMake)
- **VSCode Version**: 1.24.1
- **CMake Tools Extension Version**: 1.0.1

### Other Notes/Information

I feel like I'm missing some obvious step..? Unfamiliar with VSCode. (Not even sure how to copy the dev log cleanly...)

**Comment by vector-of-bool** [comment]
That's an odd error...

You can get to the dev log with `Help > Toggle Developer Tools`. Open the "Console" tab and that's where the devtools log will be.

**Comment by gajop** [comment]
This seems to be the entirety of the log:
```
/E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1311  INFO no standard startup: panel is active
/E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:268 [Extension Host] Activating extension 'vector-of-bool.cmake-tools' failed: Cannot read property 'replace' of undefined.
t.log @ /E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:268
/E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:268 [Extension Host] Activating extension `vector-of-bool.cmake-tools` failed:  Cannot read property 'replace' of undefined
t.log @ /E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:268
/E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:268 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'replace' of undefined
	at Function.e.file (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:46:970)
	at Function.loadForPath (C:\Users\gajo_\.vscode\extensions\vector-of-bool.cmake-tools-1.0.1\out\src\config.js:83:76)
	at Function.createForDirectory (C:\Users\gajo_\.vscode\extensions\vector-of-bool.cmake-tools-1.0.1\out\src\config.js:72:42)
	at Function.createForDirectory (C:\Users\gajo_\.vscode\extensions\vector-of-bool.cmake-tools-1.0.1\out\src\workspace.js:31:53)
	at activate (C:\Users\gajo_\.vscode\extensions\vector-of-bool.cmake-tools-1.0.1\out\src\extension.js:28:45)
	at Function.t._callActivateOptional (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:411)
	at Function.t._callActivate (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:90)
	at e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:760:118
	at Object.g [as _notify] (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:971)
	at Object.enter (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:80:277)
	at n.Class.derive._oncancel._run (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._oncancel._completed (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:523)
	at c (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:1011)
	at K.then.o.(anonymous function) (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:205)
	at Object.g [as _notify] (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:971)
	at Object.enter (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:80:277)
	at n.Class.derive._oncancel._run (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._oncancel._completed (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:523)
	at c (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:1011)
	at K.then.o.(anonymous function) (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:205)
	at Object.g [as _notify] (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:971)
	at Object.enter (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:80:277)
	at n.Class.derive._oncancel._run (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._oncancel._completed (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:523)
	at e.resolveOk (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:545:791)
	at e._receiveReply (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:165)
	at e._receiveOneMessage (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:473)
	at e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (e:\apps\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
/E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2958 Activating extension 'vector-of-bool.cmake-tools' failed: Cannot read property 'replace' of undefined.
w._logMessageInConsole @ /E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2958
/E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2265 Error: command 'cmake.quickStart' not found
    at t._tryExecuteCommand (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2736:332)
    at file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2736:187
    at Object.g [as _notify] (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at l (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:157:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:45)
    at Object.g [as _notify] (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at l (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:157:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:45)
    at Object.g [as _notify] (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._creator._run (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._creator._completed (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at Object.g [as _notify] (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at e.resolveOk (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2872:954)
    at e._receiveReply (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2937:345)
    at e._receiveOneMessage (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2936:661)
    at file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2935:518
    at file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2938:575
    at e.fire (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:169:992)
    at Socket.<anonymous> (file:///E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:301:187)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
e.onDidNotificationChange @ /E:/apps/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2265
```

Is there some precondition I should have satisfied before installing cmake tools? Some other program that needs to be installed, or some setup that needs to be configured?

**Comment by gajop** [comment]
I think I figured out what the issue was! I wasn't in folder mode (project mode?) or whatever that is. I guess I was just opening files, and there was no folder opened. I noticed this by running into this issue, where VSCode was telling me to `Open a folder first to edit configuration`...
Anyway, maybe best if you had a similar error reported to the user.
